export const sizes = {
  logoCell: 10,
  heroCell: 14,
  dot: 8,
  tabIcon: 22,
  icon: 20,
  iconSmall: 14,
  progressBar: 10,
  progressBarSmall: 6,
  badge: 44,
  badgeLarge: 48,
  avatar: 42,
  avatarLarge: 84,
  avatarRing: 5,
  streakSquare: 8,
  inputBorder: 1.5,
  hairline: 1,

  gameChip: 32,
  promptRing: 110,
  promptRingBorder: 3,
  timelineDot: 26,
  timelineDotBorder: 2,
  meterThick: 12,
  levelTile: 64,
  legendSwatch: 20,
  targetGridMaxWidth: 300,
} as const;

export type Sizes = typeof sizes;
