export const sizes = {
  logoCell: 10,
  heroCell: 14,
  dot: 8,
  tabIcon: 22,
  icon: 20,
  iconSmall: 14,
  progressBar: 10,
  progressBarSmall: 6,
  badge: 44,
  badgeLarge: 48,
  avatar: 42,
  avatarLarge: 84,
  avatarRing: 5,
  streakSquare: 8,
  inputBorder: 1.5,
  hairline: 1,

  gameChip: 32,
  promptRing: 110,
  promptRingBorder: 3,
  timelineDot: 26,
  timelineDotBorder: 2,
  meterThick: 12,
  levelTile: 64,
  legendSwatch: 20,
  targetGridMaxWidth: 300,

  chartHeight: 112,
  chartLineHeight: 96,
  chartStroke: 2.5,
  chartDot: 3.5,
  chartBarMaxWidth: 22,
  chartBarMinGap: 2,
  chartAxisWidth: 38,
  podiumAvatar: 52,
  podiumAvatarLeader: 64,
  podiumColumnWidth: 96,
  podiumStepLeader: 88,
  podiumStepSecond: 64,
  podiumStepThird: 48,
  rankColumn: 34,
  rowAvatar: 36,
  heatmapMaxWidth: 240,
  swatch: 12,
  statusDot: 10,
} as const;

export type Sizes = typeof sizes;
